### ISSUE TITLE
Hi-C sample data needed

### ISSUE THREAD

**Issue by gswsqffsapd3056** [NBStarry/CGMega#1]
We are very interested in your work and have benefited from it. We also want to learn the idea of multi-omics analysis from your method. However, we noticed that the download link for the example data does not point to a valid link. If it is convenient, could you please update the download link for the Hi-C dataset? Thank you very much.

**Comment by NBStarry** [comment]
We have uploaded the example data to `https://drive.google.com/drive/folders/1w4GGIZRUNevTkWUSsLKPNS5AliHeOvi8?usp=sharing`.

**Comment by gswsqffsapd3056** [comment]
Thank you for sharing the data! The model worked
